description: Registry containing 10 dummy models for testing
models:
  dummy-model-1:
    config_file: models/dummy-model-1.yaml
    id: dummy-model-1
  dummy-model-10:
    config_file: models/dummy-model-10.yaml
    id: dummy-model-10
  dummy-model-2:
    config_file: models/dummy-model-2.yaml
    id: dummy-model-2
  dummy-model-3:
    config_file: models/dummy-model-3.yaml
    id: dummy-model-3
  dummy-model-4:
    config_file: models/dummy-model-4.yaml
    id: dummy-model-4
  dummy-model-5:
    config_file: models/dummy-model-5.yaml
    id: dummy-model-5
  dummy-model-6:
    config_file: models/dummy-model-6.yaml
    id: dummy-model-6
  dummy-model-7:
    config_file: models/dummy-model-7.yaml
    id: dummy-model-7
  dummy-model-8:
    config_file: models/dummy-model-8.yaml
    id: dummy-model-8
  dummy-model-9:
    config_file: models/dummy-model-9.yaml
    id: dummy-model-9
name: Dummy Model Registry
version: 1.0.0
