#!/bin/bash

# Start dummy model APIs
# This script is auto-generated by create_dummy_models.py

# Start apple_model
python -m scripts.create_dummy_models --run-server --model-index 0 &
echo "Started apple_model on port 8001"

# Start orange_model
python -m scripts.create_dummy_models --run-server --model-index 1 &
echo "Started orange_model on port 8002"

# Wait for any key to terminate all processes
read -p "Press any key to terminate all dummy models..."

# Kill all background processes
kill $(jobs -p)
